//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinomaks
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmTimetable
    {
        public int ID { get; set; }
        public int IDFilm { get; set; }
        public int IDTimeTable { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Timetable Timetable { get; set; }
    }
}
