//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinomaks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KinomaksEntities : DbContext
    {
        public KinomaksEntities()
            : base("name=KinomaksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<FilmTimetable> FilmTimetable { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<HallTimetable> HallTimetable { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
