//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinomaks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public int ID { get; set; }
        public int Number { get; set; }
        public int IDHall { get; set; }
    
        public virtual Hall Hall { get; set; }
    }
}
